Factor out ssh signal function

diff --git a/bin/common b/bin/common
--- a/bin/common
+++ b/bin/common
@@ -94,28 +94,15 @@ signal () {
 
     if [[ all = ${PUSHTYPE} ]]; then
         # Default normal "fire and forget" push. We background that, we do not care about the mirrors doings
-        log "Sending normal push" >> "${LOGDIR}/${MIRROR}.log"
         PUSHARGS1="sync:all"
-        ssh -n $SSH_OPTIONS "${HOSTNAME}" "${PUSHARGS} ${PUSHARGS1}" >>"${LOGDIR}/${MIRROR}.log" 2>&1
-        if [[ $? -eq 255 ]]; then
-            error "Trigger to ${HOSTNAME} failed"  >> "${LOG}"
-        else
-            log "Trigger to ${HOSTNAME} succeed" >> "${LOG}"
-        fi
+        signal_ssh "normal" "${MIRROR}" "${HOSTNAME}" $SSH_OPTIONS "${PUSHARGS} ${PUSHARGS1}"
     elif [[ staged = ${PUSHTYPE} ]] || [[ mhop = ${PUSHTYPE} ]]; then
         # Want a staged push. Fine, lets do that. Not backgrounded. We care about the mirrors doings.
-        log "Sending staged push" >> "${LOGDIR}/${MIRROR}.log"
-
         # Only send stage1 if we havent already send it. When called with stage2, we already did.
         if [[ stage2 != ${PUSHKIND} ]]; then
             # Step1: Do a push to only sync stage1, do not background
             PUSHARGS1="sync:stage1"
-            ssh -n $SSH_OPTIONS "${HOSTNAME}" "${PUSHARGS} ${PUSHARGS1}" >>"${LOGDIR}/${MIRROR}.log" 2>&1
-            if [[ $? -eq 255 ]]; then
-                error "Trigger to ${HOSTNAME} failed"  >> "${LOG}"
-            else
-                log "Trigger to ${HOSTNAME} succeed" >> "${LOG}"
-            fi
+            signal_ssh "staged" "${MIRROR}" "${HOSTNAME}" $SSH_OPTIONS "${PUSHARGS} ${PUSHARGS1}"
             touch "${PUSHLOCKOWN}"
 
             # Step2: Wait for all the other "lock"files to appear.
@@ -144,17 +131,26 @@ signal () {
             return
         else
             PUSHARGS2="sync:stage2"
-            log "Now doing the second stage push" >> "${LOGDIR}/${MIRROR}.log"
-            ssh -n $SSH_OPTIONS "${HOSTNAME}" "${PUSHARGS} ${PUSHARGS2}" >>"${LOGDIR}/${MIRROR}.log" 2>&1
-            if [[ $? -eq 255 ]]; then
-                error "Trigger to ${HOSTNAME} failed"  >> "${LOG}"
-            else
-                log "Trigger to ${HOSTNAME} succeed" >> "${LOG}"
-            fi
+            signal_ssh "second stage" "${MIRROR}" "${HOSTNAME}" $SSH_OPTIONS "${PUSHARGS} ${PUSHARGS2}"
         fi
     else
         # Can't decide? Then you get nothing.
         return
+    fi
+}
+
+signal_ssh() {
+    local t=$1
+    local mirror_log="${LOGDIR}/${2}.log"
+    local hostname=$3
+    shift 3
+
+    log "Sending ${t} push" >> $mirror_log
+    ssh -n $hostname "$@" >> $mirror_log 2>&1
+    if [[ $? -eq 255 ]]; then
+        error "Trigger to $hostname failed"  >> "${LOG}"
+    else
+        log "Trigger to $hostname succeed" >> "${LOG}"
     fi
 }
 
