Check only the archive serial in cron wrapper

diff --git a/bin/ftpsync-cron b/bin/ftpsync-cron
--- a/bin/ftpsync-cron
+++ b/bin/ftpsync-cron
@@ -40,11 +40,12 @@ function cmp_trace() {
         exit $ret
     fi
 
-    if ! [[ -e "$trace_local" ]]; then
+    if ! serial_remote=$(extract_trace_serial <<< $trace); then
+        error "Failed to parse archive serial from $trace_uri"
+        exit 1
+    elif ! serial_local=$(extract_trace_serial $trace_local); then
         return 1
-    elif echo "$trace" | cmp --silent - "$trace_local"; then
-        return 0
-    else
+    elif [[ $serial_remote != $serial_local ]]; then
         return 1
     fi
 }
